[versions]
agp = "8.2.2"
androidx-activityCompose = "1.8.2"
coroutines = "1.7.3"
compose-plugin = "1.6.0-beta01"
kotlin = "1.9.21"
voyager = "1.0.0"
coil3-io = "3.0.0-alpha02"
ktor = "2.3.7"
[libraries]
androidx-activity-compose= { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
voyager-screenmodel={module="cafe.adriel.voyager:voyager-screenmodel",version.ref="voyager"}
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }
voyager-transitions = { group = "cafe.adriel.voyager", name = "voyager-transitions", version.ref = "voyager" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }


coil3 = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3-io" }
coil3-network = { module = "io.coil-kt.coil3:coil-network", version.ref = "coil3-io" }
coil3-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil3-io" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

